
USE master;  
GO  
ALTER DATABASE FinanceWork SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE FinanceWork MODIFY NAME = FinanceWorkCurrent;
GO  
ALTER DATABASE FinanceWorkCurrent SET MULTI_USER;
GO

ALTER DATABASE FinanceWork2 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE FinanceWork2 MODIFY NAME = FinanceWork;
GO  
ALTER DATABASE FinanceWork SET MULTI_USER;
GO
