
/**************************************************************************************************************************
Date		: 2022/01/30
Create by	: DBAs AMS
Object		: [dbo].[PolicyCheck_CreateUser]
Description	: This SP is use to create user with POLICY CHECKED in ON.
Exec Command: EXEC [dbo].[PolicyCheck_CreateUser]
**************************************************************************************************************************/

IF EXISTS (SELECT NAME FROM SYS.PROCEDURES WHERE NAME = 'PolicyCheck_CreateUser')
	DROP PROCEDURE [dbo].[PolicyCheck_CreateUser]
GO

CREATE PROC [dbo].[PolicyCheck_CreateUser]
AS
BEGIN
	
	SET NOCOUNT ON

	-- Declare var
	DECLARE @var_Name	  NVARCHAR(255) = ''
		,	@var_SQL	  NVARCHAR(255) = ''
		,	@var_Message  NVARCHAR(MAX) = ''

	-- Declare var table
	DECLARE @UserName TABLE
	(
		  PK_ID		NUMERIC(18,0) NOT NULL IDENTITY(1, 1)
		, UserName	NVARCHAR(20)  NOT NULL
	)

	-- Create var to LOOP the bucle
	DECLARE @var_Rows	NUMERIC
		,	@var_i		NUMERIC(18, 0)

	-- Set vars
	SET @var_Rows = 0
	SET	@var_i	  = 1 

	-- Insert data into var table
	INSERT INTO @UserName (UserName)	
	SELECT [NAME]
	FROM   SYS.SQL_LOGINS 
	WHERE  [Type] = 'S' 
	AND    [Is_policy_checked] = 0

	-- Set @var_Rows with the total amount of records
	SET @var_Rows = (SELECT TOP 1 PK_ID FROM @UserName ORDER BY PK_ID DESC )

	-- Loop until we create all new users
	WHILE @var_i <= @var_Rows
	BEGIN

		-- Declare var inside the LOOP
		DECLARE @Loop_UserName NVARCHAR(20)

		-- Select user to by create
		SELECT @Loop_UserName = UserName FROM @UserName WHERE PK_ID = @var_i

		-- Create user
		SELECT @var_SQL = 'ALTER LOGIN ' + @Loop_UserName + ' WITH CHECK_POLICY = ON;'

		-- For testing
		-- SELECT @var_SQL

		-- Exec command
		EXEC (@var_SQL)
		
		-- Set var to send info by email
		IF @var_Name = ''
			SET @var_Name = @Loop_UserName
		ELSE
			SET @var_Name = @var_Name + '; ' + @Loop_UserName

		-- Increase @var_i
		SET @var_i = @var_i + 1

	END

	-- Set message to send
	SELECT @var_Message = @var_Message + 
	'Note: This is an automatic e-mail message generated by Company.  
		   
	Following users were created with Policy Check ON.
		   
	' + @var_Name + 
		 
	'
	Thank you!
	Company, Inc.'

	-- For Test message
	SELECT @var_Message

	-- Send mail with info
	IF @var_Rows <> 0
	  BEGIN
			EXEC msdb..sp_send_dbmail @profile_name = 'SQL USR Profile' 
		   ,@recipients ='jose.noriega@optum.com;lucas.liberatori@perficient.com' 
		   ,@subject	= 'Password Policy in TSM-EDPSQL01'
		   ,@body		= @var_Message
		   ,@execute_query_database = 'master'
		   ,@query_result_width		= 1000
	  END

END

GO
